# Change these first
owner: Proxeuse # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: API - Cloud Servers
    check: "tcp-ping"
    url: api.hetzner.cloud
    port: 443
  - name: API - Domain Registration
    check: "tcp-ping"
    url: api.openprovider.eu
    port: 443
  - name: API - Payments via PayPal
    check: "tcp-ping"
    url: api-m.paypal.com
    port: 443
  - name: API - Payments via Stripe
    check: "tcp-ping"
    url: api.stripe.com
    port: 443
  - name: Nextcloud - Storage Backend
    check: "tcp-ping"
    url: $NEXTCLOUD
    port: 80
  - name: Plesk - Falkenstein (DE)
    check: "tcp-ping"
    url: cloud.proxweb.eu
    port: 8443
  - name: Service - Customer Portal
    url: https://my.proxeuse.com
  - name: Service - Documentation
    url: https://docs.proxeuse.com
  - name: Service - Downloads Portal
    url: https://downloads.proxeuse.nl
  - name: Service - Help Center
    url: $HELP_URL
  - name: Service - Portainer
    url: https://portainer.proxeuse.com
  - name: Service - Pterodactyl
    url: https://pterodactyl.proxeuse.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.proxeuse.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Proxeuse Status
  introTitle: "**Proxeuse Status**"
  introMessage: This is the status page of Proxeuse which uses **real-time** data from our [GitHub repository](https://github.com/Proxeuse/Status) and [Uptime Montitoring software](https://uptime.proxeuse.com).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/15 * * * *"
